id: swift-webview-config-base-url-swift
severity: warning
language: swift
message: >-
  UIWebView instances were observed where the baseURL is misconfigured as
  nil, which allows for origin abuse within the webview. In order to remove
  the effective origin, the application should explicitly set the baseURL to
  `about:blank` or similar.
note: >-
  [CWE-272] Least Privilege Violation.
  [REFERENCES]
      - https://mas.owasp.org/MASVS/controls/MASVS-PLATFORM-2/
utils:
  matches_patttern_loadHTMLString_&_load:
    kind: call_expression
    all:
      - has:
          stopBy: end
          kind: navigation_expression
          all:
            - has:
                stopBy: end
                kind: simple_identifier
                pattern: $W
            - has:
                stopBy: end
                kind: navigation_suffix
                has:
                  stopBy: end
                  kind: simple_identifier
                  regex: "^loadHTMLString|load$"
      - has:
          stopBy: end
          kind: call_suffix
          has:
            stopBy: end
            kind: value_argument
            all:
              - has:
                  stopBy: end
                  kind: simple_identifier
                  regex: "^baseURL$"
              - has:
                  stopBy: end
                  regex: "^nil$"
      - follows:
          stopBy: end
          kind: property_declaration
          all:
            - all:
                - has:
                    stopBy: end
                    kind: pattern
                    has:
                      stopBy: end
                      kind: simple_identifier
                      pattern: $W
                - has:
                    stopBy: end
                    kind: call_expression
                    pattern: UIWebView(...)

rule:
  kind: call_expression
  matches: matches_patttern_loadHTMLString_&_load
